version: 5
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:73DF-1002:0E36-0000:2d:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: edge
      interval_ms: 500
      curve:
        50: 0.15
        63: 0.37
        72: 0.57
        77: 0.7
        85: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    power_cap: 186.0
    performance_level: auto
    max_core_clock: 2600
    voltage_offset: -90
current_profile: null
auto_switch_profiles: false
